node {

    echo 'entered Jenkins'
    echo "env -  ${env.BRANCH_NAME}"
    echo "${env}"
    echo "${env.BRANCH_NAME}"
    echo env
    echo env.BRANCH_NAME
    def envJenkinsfile


    if (env.BRANCH_NAME.equals('dev')) {
        echo "enetered in dev branch"
        envJenkinsfile = 'dev.Jenkinsfile'
        echo "envJenkins file ${envJenkinsfile}"

    } else {
        echo "Branch does not match any enviornment"
        return
    }

    echo "loading envJenkinsfile"
    load envJenkinsfile
}