node {

    def envJenkinsfilePath

    if (env.BRANCH_NAME.equals('dev')) {
        envJenkinsfilePath = "${env.ENV_JENKINSFILE_PATH}/dev.Jenkinsfile"

    } else {
        echo "Branch environment does not exist"
        return
    }

    load envJenkinsfilePath
}
