node {
    if (env.BRANCH_NAME.equals('dev')) {
        echo "enetered in dev branch"
        envJenkinsfile = 'configs/jenkins/dev.Jenkinsfile'
        echo "envJenkins file ${envJenkinsfile}"

    } else {
        echo "Branch does not match any enviornment"
        return
    }

    echo "result - ${env.JENKINSFILE_ENV_PATH}/dev.Jenkinsfile"
    echo "loading envJenkinsfile"
    // load envJenkinsfile
    // load 'configs/jenkins/dev.Jenkinsfile'
    // load './dev.Jenkinsfile'
    // load './dev.Jenkinsfile'
    load "${env.JENKINSFILE_ENV_PATH}/dev.Jenkinsfile"
    echo "done loading envJenkinsfile"
}